version: '3.8'

services:
  yarp-gateway:
    build:
      context: ./Yarp-microservices-example
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - microservicesnetwork

  user-api:
    build:
      context: ./User-microservices-example
      dockerfile: Dockerfile
    networks:
      - microservicesnetwork

  user-postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: userDatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  
  blog-api:
    build:
      context: ./Blog-microservices-example
      dockerfile: Dockerfile
    networks:
      - microservicesnetwork

networks:
  microservicesnetwork:
    driver: bridge
